config/routes.rb
FortuneRookie::Application.routes.draw do
  root to: 'users#show'
  devise_for :users

  resources :buys, only: [:new, :create]
  resources :payments, only: [:new, :create]
  resources :players, only: [:index, :show]
  resources :sells, only: [:new, :create]
  resources :users, only: :show

  get '/buys/new/:id', to: 'buys#new'
  get '/sells/new/:id', to: 'sells#new'
  get '/services/:id', to: 'services#player_stats'
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :holdings

  def balance_as_money
    "$#{'%.2f' % (balance / 100.0)}"
  end

  def braintree_payment(amount)
    update_attributes(balance: balance + amount)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # include UserHelper

  def show
    @transactions = Transaction.where("buyer_id = ? or seller_id = ?", current_user.id, current_user.id).limit(5)
  end
end

app/views/users/show.html.haml
%h3
  Welcome
  = current_user.email
%span
  We pay $100 for every rookie that becomes a first round draft pick.
%br
%span
  Browse the players, and purchase shares.
%br
%span
  If you choose wisely, you could win.
%br
%br
%span
  There are two possible outcomes for each player:
%br
%span
  the player is drafted in the first round, or not.
%br
%span
  Your opinion on what the outcome will be determines whether you buy or sell shares:
%br
%span
If you predict the player will be drafted then you BUY shares.
%br
%span
If you predict the player will not be drafted then you SELL shares.
%br
%br
%h4
  Your account balance is
  = current_user.balance_as_money
  = link_to 'Add Money', new_payment_path
  to purchase shares.
%br
%br
.row
  %h5.small-3.columns
    Your recent transactions
-if @transactions.present?
  .row
    %span.small-3.columns
      Player
    %span.small-2.columns
      Price paid
    %span.small-7.columns
  - @transactions.each do |transaction|
    .row
      %span.small-3.columns
        =link_to "#{transaction.player.first_name} #{transaction.player.last_name}", transaction.player
      %span.small-2.columns
        = transaction.price_in_dollars
      %span.small-7.columns
-else
  %span.small-3.columns
    You have no recent transactions.
%br
%br
.row
  %h5.small-3.columns
    Your holdings
- if current_user.holdings.present?
  .row
    %span.small-3.columns
      Player
    %span.small-2.columns
      Shares
    %span.small-2.columns
      Price paid
    %span.small-5.columns
  - current_user.holdings.each do |holding|
    .row
      %span.small-3.columns
        =link_to "#{holding.player.first_name} #{holding.player.last_name}", holding.player
      %span.small-2.columns
        = holding.shares
      %span.small-2.columns
        = holding.cash_per_share
      %span.small-5.columns
-else
  %span.small-3.columns
    You have no holdings.