config/routes.rb
FortuneRookie::Application.routes.draw do
  root to: 'users#show'
  devise_for :users

  resources :buys, only: [:new, :create]
  resources :payments, only: [:new, :create]
  resources :players, only: [:index, :show]
  resources :sells, only: [:new, :create]
  resources :users, only: :show

  get '/buys/new/:id', to: 'buys#new'
  get '/sells/new/:id', to: 'sells#new'
  get '/services/:id', to: 'services#player_stats'
end

app/models/player.rb
class Player < ActiveRecord::Base

  before_create :set_current_price
  before_create :set_ask_price
  after_create :create_sell

  validates :first_name,    presence: true
  validates :last_name,     presence: true
  validates :draft_year,    presence: true
  validates :ipo,           presence: true
  validates :current_price, presence: true
  validates :last_ask,      presence: true

  def current_price_in_dollars
    "$#{'%.2f' % (current_price / 100.0)}"
  end

  def ask_price_in_dollars
    "$#{'%.2f' % (last_ask / 100.0)}"
  end

  def set_current_price
    self.current_price = ipo
  end

  def set_ask_price
    self.last_ask = 0
  end

  def create_sell
    admin = User.find_by(email: 'admin@admin.com')
    Sell.create(player_id: id, seller_id: admin.id, price: ipo, shares: 1, role: 'pending')
    admin.holdings << Holding.create(player_id: id, user_id: admin.id, price_per_share: ipo, shares: 1)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def index
    @players = Player.where(draft_year: Time.now.year)
  end

  def show
    @player = Player.find_by(id: params[:id])
    @players = Player.where(position: @player.position)
    @players.reject!{|player| player.id == @player.id}
    @holdings = current_user.holdings.reject{|player| player.id == @player.id}
  end

end

app/views/players/index.html.haml
%h2
  = Time.now.year
  Draft
-if @players.present?
  - @players.each do |player|
    %ul
      %li
        =link_to player do
          = player.first_name
          = player.last_name
        = link_to 'Buy', "/buys/new/#{player.id}"
        -if current_user.holdings.any?{|holding| holding.player_id == player.id}
          = link_to 'Sell', "/sells/new/#{player.id}"
      %li
        Current Price
        = player.current_price_in_dollars
      %li
        Last Ask
        -if player.last_ask == 0
          No last ask
        -else
          = player.ask_price_in_dollars
-else
  %li No players held.

app/views/players/show.html.haml
%h2
  = @player.first_name + " " + @player.last_name
  = @player.school
  = @player.position

//= link_to "Buy Now", buy_new_path(@player.id)

%div#chart_div

%h2 Jump to your other players
%ul
-if @holdings.present?
  - @holdings.each do |holding|
    %li= link_to "#{holding.player.first_name} #{holding.player.last_name}", holding.player
-else
  %li You have no other holdings.

%h2 Jump to other players
%ul
-if @players.present?
  - @players.each do |player|
    %li= link_to player.first_name + " " + player.last_name, player_path(player)
-else
  %li= "There are no other players that play #{player.position}"


%h2 Latest News

#services{data: { 'player-id' => "#{@player.id}", 'data-points' => ''} }